// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB94L1ytlhzyuMe9JCafNWY4ZqtvAOpvrs',
    appId: '1:1063890324102:web:516489cab1d46548e3df07',
    messagingSenderId: '1063890324102',
    projectId: 'social-a4aca',
    authDomain: 'social-a4aca.firebaseapp.com',
    storageBucket: 'social-a4aca.appspot.com',
    measurementId: 'G-1KJCXJZMND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYfIuMdJeNflDoihuMKtnUQBLXUSoS1Y',
    appId: '1:1063890324102:android:b56bbb85e5335c99e3df07',
    messagingSenderId: '1063890324102',
    projectId: 'social-a4aca',
    storageBucket: 'social-a4aca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfomAE4SV9q2Mgv61W2MHPfG2ha0odvys',
    appId: '1:1063890324102:ios:eb4ac7ccfc493aeae3df07',
    messagingSenderId: '1063890324102',
    projectId: 'social-a4aca',
    storageBucket: 'social-a4aca.appspot.com',
    androidClientId: '1063890324102-da11mdfrk6gov2n63t2nv7pq987sln2d.apps.googleusercontent.com',
    iosClientId: '1063890324102-ea93jc6etnbh1b50civ7kqphce0thflf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfomAE4SV9q2Mgv61W2MHPfG2ha0odvys',
    appId: '1:1063890324102:ios:eb4ac7ccfc493aeae3df07',
    messagingSenderId: '1063890324102',
    projectId: 'social-a4aca',
    storageBucket: 'social-a4aca.appspot.com',
    androidClientId: '1063890324102-da11mdfrk6gov2n63t2nv7pq987sln2d.apps.googleusercontent.com',
    iosClientId: '1063890324102-ea93jc6etnbh1b50civ7kqphce0thflf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
